// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ORM_Components;

#nullable disable

namespace ORM_Components.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250303113049_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ORM_Components.Tables.BankCardTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("card_number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("cvv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("money_value")
                        .HasColumnType("bigint");

                    b.Property<string>("name_card")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("bankCardTable");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e11ba92a-649b-4ea7-8881-c4d7840be3a0"),
                            card_number = "0000 1234 0000 4321",
                            cvv = "123",
                            money_value = 1000000L,
                            name_card = "Virtual Card"
                        });
                });

            modelBuilder.Entity("ORM_Components.Tables.BasketTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("food_item_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("basketTable");
                });

            modelBuilder.Entity("ORM_Components.Tables.CardUsersTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("card_number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("cvv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("money_value")
                        .HasColumnType("bigint");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("cardUsersTable");
                });

            modelBuilder.Entity("ORM_Components.Tables.CourierTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("car_number")
                        .HasColumnType("text");

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.Property<Guid>("userId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("courierTable");
                });

            modelBuilder.Entity("ORM_Components.Tables.OrderItemsTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("order_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("restaraunt_food_item")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("orderItemsTable");
                });

            modelBuilder.Entity("ORM_Components.Tables.OrderStatusHistoryTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("order_id")
                        .HasColumnType("uuid");

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("status_datetime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("orderHistory");
                });

            modelBuilder.Entity("ORM_Components.Tables.OrderTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("client_id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("courier_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("order_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("restaurant_id")
                        .HasColumnType("uuid");

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.Property<long>("total_price")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("orderTable");
                });

            modelBuilder.Entity("ORM_Components.Tables.PayTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("card_number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("pay_status")
                        .HasColumnType("integer");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("payTable");
                });

            modelBuilder.Entity("ORM_Components.Tables.RequestTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("courier_id")
                        .HasColumnType("uuid");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("restaurant_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("time_add")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("requestTable");
                });

            modelBuilder.Entity("ORM_Components.Tables.RestaurantFoodItemsTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("calories")
                        .HasColumnType("integer");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("price")
                        .HasColumnType("bigint");

                    b.Property<Guid>("restaurant_id")
                        .HasColumnType("uuid");

                    b.Property<int>("weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("restaurantFoodItemsTable");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0d6cf45-f6c9-460f-9023-b2aa533453d7"),
                            calories = 2000,
                            image = "NONE",
                            name = "Тестовое блюдо",
                            price = 1000L,
                            restaurant_id = new Guid("54d33061-3691-4b7d-a60c-c53ef2e4eb4e"),
                            weight = 100
                        },
                        new
                        {
                            Id = new Guid("d32dbf53-af51-4bf4-b751-0b6f9b2ae02d"),
                            calories = 1000,
                            image = "NONE",
                            name = "Тестовое блюдо 2",
                            price = 1200L,
                            restaurant_id = new Guid("54d33061-3691-4b7d-a60c-c53ef2e4eb4e"),
                            weight = 100
                        });
                });

            modelBuilder.Entity("ORM_Components.Tables.RestaurantTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("close_time")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("imagePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("open_time")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("phone_number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("restaurantName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("restaurantTable");

                    b.HasData(
                        new
                        {
                            Id = new Guid("54d33061-3691-4b7d-a60c-c53ef2e4eb4e"),
                            address = "ул. Шолмова 5",
                            close_time = "21:00",
                            description = "Отличный тестовый ресторан",
                            imagePath = "NONE",
                            open_time = "10:00",
                            phone_number = "+78005555535",
                            restaurantName = "Тестовый ресторан",
                            status = 1,
                            user_id = new Guid("1993856e-2f5c-4790-a3d4-33e6a5718b47")
                        },
                        new
                        {
                            Id = new Guid("330fbf17-55f3-44cb-8114-75f05f02431b"),
                            address = "ул. Шолмова 3",
                            close_time = "20:00",
                            description = "Хороший тестовый ресторан",
                            imagePath = "NONE",
                            open_time = "10:00",
                            phone_number = "+78004444434",
                            restaurantName = "Тестовый ресторан 2",
                            status = 1,
                            user_id = new Guid("1993856e-2f5c-4790-a3d4-33e6a5718b47")
                        });
                });

            modelBuilder.Entity("ORM_Components.Tables.ReviewTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("client_id")
                        .HasColumnType("uuid");

                    b.Property<string>("comment")
                        .HasColumnType("text");

                    b.Property<Guid?>("courier_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("order_id")
                        .HasColumnType("uuid");

                    b.Property<int>("rating")
                        .HasColumnType("integer");

                    b.Property<Guid?>("restaurant_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("review_date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("reviewTable");
                });

            modelBuilder.Entity("ORM_Components.Tables.UserTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("address")
                        .HasColumnType("text");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("last_name")
                        .HasColumnType("text");

                    b.Property<long>("money_value")
                        .HasColumnType("bigint");

                    b.Property<string>("photo_url")
                        .HasColumnType("text");

                    b.Property<string[]>("roles")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<long>("telegram_chat_id")
                        .HasColumnType("bigint");

                    b.Property<long>("telegram_id")
                        .HasColumnType("bigint");

                    b.Property<string>("username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("userTable");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1993856e-2f5c-4790-a3d4-33e6a5718b47"),
                            address = "улица Шолмова, 7",
                            first_name = "Антон (Study)",
                            last_name = "",
                            money_value = 5000L,
                            photo_url = "https://t.me/i/userpic/320/YC895p02kbd-O-aU-F49vK8j1qFbmbObwS_DaaPkKdg.svg",
                            roles = new[] { "Client", "Admin", "Courier" },
                            telegram_chat_id = 1006365928L,
                            telegram_id = 1006365928L,
                            username = "studywhite"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
