// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ORM_Components;

#nullable disable

namespace ORM_Components.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250331182704_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ORM_Components.Tables.BankCardTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("card_number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("cvv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("money_value")
                        .HasColumnType("bigint");

                    b.Property<string>("name_card")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("bankCardTable");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e11ba92a-649b-4ea7-8881-c4d7840be3a0"),
                            card_number = "0000 1234 0000 4321",
                            cvv = "123",
                            money_value = 1000000L,
                            name_card = "Virtual Card"
                        });
                });

            modelBuilder.Entity("ORM_Components.Tables.BasketTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("food_item_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("basketTable");
                });

            modelBuilder.Entity("ORM_Components.Tables.CardUsersTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("card_number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("cvv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("money_value")
                        .HasColumnType("bigint");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("cardUsersTable");
                });

            modelBuilder.Entity("ORM_Components.Tables.CourierTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("car_number")
                        .HasColumnType("text");

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.Property<Guid>("userId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("courierTable");
                });

            modelBuilder.Entity("ORM_Components.Tables.OrderItemsTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("order_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("restaraunt_food_item")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("orderItemsTable");
                });

            modelBuilder.Entity("ORM_Components.Tables.OrderStatusHistoryTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("order_id")
                        .HasColumnType("uuid");

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("status_datetime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("orderHistory");
                });

            modelBuilder.Entity("ORM_Components.Tables.OrderTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("client_id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("courier_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("order_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("restaurant_id")
                        .HasColumnType("uuid");

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.Property<long>("total_price")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("orderTable");
                });

            modelBuilder.Entity("ORM_Components.Tables.PayTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("card_number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("pay_status")
                        .HasColumnType("integer");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("payTable");
                });

            modelBuilder.Entity("ORM_Components.Tables.RequestTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("courier_id")
                        .HasColumnType("uuid");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("restaurant_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("time_add")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("requestTable");
                });

            modelBuilder.Entity("ORM_Components.Tables.RestaurantFoodItemsTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("calories")
                        .HasColumnType("integer");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("price")
                        .HasColumnType("bigint");

                    b.Property<Guid>("restaurant_id")
                        .HasColumnType("uuid");

                    b.Property<int>("weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("restaurantFoodItemsTable");

                    b.HasData(
                        new
                        {
                            Id = new Guid("df61599f-0933-49b8-9735-be616bb4e4a6"),
                            calories = 0,
                            image = "/app/migrated_images/Vkusno/chikenburger.png",
                            name = "Чикенбургер",
                            price = 82L,
                            restaurant_id = new Guid("54d33061-3691-4b7d-a60c-c53ef2e4eb4e"),
                            weight = 0
                        },
                        new
                        {
                            Id = new Guid("23e7dfb3-a218-4329-b7b8-588179e6f1d9"),
                            calories = 0,
                            image = "/app/migrated_images/Vkusno/bighit.png",
                            name = "Биг Хит",
                            price = 223L,
                            restaurant_id = new Guid("54d33061-3691-4b7d-a60c-c53ef2e4eb4e"),
                            weight = 0
                        },
                        new
                        {
                            Id = new Guid("1da2b42e-fac0-4c01-98ad-a0959f1b5d96"),
                            calories = 0,
                            image = "/app/migrated_images/Vkusno/cheezeburger.png",
                            name = "Чизбургер",
                            price = 101L,
                            restaurant_id = new Guid("54d33061-3691-4b7d-a60c-c53ef2e4eb4e"),
                            weight = 0
                        },
                        new
                        {
                            Id = new Guid("81b65cf4-29ff-4110-9d10-1a3753af4593"),
                            calories = 0,
                            image = "/app/migrated_images/Vkusno/bigspecial.png",
                            name = "Биг спешиал",
                            price = 352L,
                            restaurant_id = new Guid("54d33061-3691-4b7d-a60c-c53ef2e4eb4e"),
                            weight = 0
                        },
                        new
                        {
                            Id = new Guid("1cf13caa-6884-4a8d-8a01-5a4caea2619c"),
                            calories = 0,
                            image = "/app/migrated_images/Vkusno/cezarroll.png",
                            name = "Цезарь Ролл",
                            price = 242L,
                            restaurant_id = new Guid("54d33061-3691-4b7d-a60c-c53ef2e4eb4e"),
                            weight = 0
                        },
                        new
                        {
                            Id = new Guid("688113e8-cef7-4b41-b9d6-1b237efef01d"),
                            calories = 0,
                            image = "/app/migrated_images/Vkusno/doublecheezeburger.png",
                            name = "Двойной Чизбургер",
                            price = 195L,
                            restaurant_id = new Guid("54d33061-3691-4b7d-a60c-c53ef2e4eb4e"),
                            weight = 0
                        },
                        new
                        {
                            Id = new Guid("131ad21e-2c19-4bce-afc8-d88b56c1094d"),
                            calories = 0,
                            image = "/app/migrated_images/Vkusno/chikenpremiere.png",
                            name = "Чикен Премьер",
                            price = 214L,
                            restaurant_id = new Guid("54d33061-3691-4b7d-a60c-c53ef2e4eb4e"),
                            weight = 0
                        },
                        new
                        {
                            Id = new Guid("4b52d1e2-4029-460e-bfb2-011b474640ae"),
                            calories = 0,
                            image = "/app/migrated_images/Vkusno/potatofreesred.png",
                            name = "Картофель Фри средний",
                            price = 112L,
                            restaurant_id = new Guid("54d33061-3691-4b7d-a60c-c53ef2e4eb4e"),
                            weight = 0
                        },
                        new
                        {
                            Id = new Guid("65136a23-c7dd-48ae-b17f-a6feb4706924"),
                            calories = 0,
                            image = "/app/migrated_images/Vkusno/naggets6.png",
                            name = "Наггетсы (6 шт)",
                            price = 109L,
                            restaurant_id = new Guid("54d33061-3691-4b7d-a60c-c53ef2e4eb4e"),
                            weight = 0
                        },
                        new
                        {
                            Id = new Guid("984a10cc-b58a-40fb-bc30-6ffa96dbb45d"),
                            calories = 0,
                            image = "/app/migrated_images/Vkusno/capuchinosred.png",
                            name = "Капучино (сред.)",
                            price = 134L,
                            restaurant_id = new Guid("54d33061-3691-4b7d-a60c-c53ef2e4eb4e"),
                            weight = 0
                        },
                        new
                        {
                            Id = new Guid("0983151c-9ba3-4900-b494-07e99a10cb0c"),
                            calories = 0,
                            image = "/app/migrated_images/Vkusno/vishnyapirojok.png",
                            name = "Пирожок Вишневый",
                            price = 84L,
                            restaurant_id = new Guid("54d33061-3691-4b7d-a60c-c53ef2e4eb4e"),
                            weight = 0
                        });
                });

            modelBuilder.Entity("ORM_Components.Tables.RestaurantTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("close_time")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("imagePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("open_time")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("phone_number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("restaurantName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("restaurantTable");

                    b.HasData(
                        new
                        {
                            Id = new Guid("54d33061-3691-4b7d-a60c-c53ef2e4eb4e"),
                            address = "ул. Шолмова 5",
                            close_time = "21:00",
                            description = "Отличный тестовый ресторан",
                            imagePath = "/app/migrated_images/vkusno.jpg",
                            open_time = "10:00",
                            phone_number = "+78005555535",
                            restaurantName = "Вкусно и точка",
                            status = 1,
                            user_id = new Guid("1993856e-2f5c-4790-a3d4-33e6a5718b47")
                        },
                        new
                        {
                            Id = new Guid("1d55fc0c-6f29-4980-9855-4a3397d1be20"),
                            address = "ул. Шолмова 3",
                            close_time = "20:00",
                            description = "Хороший тестовый ресторан",
                            imagePath = "/app/migrated_images/burgerking.jpg",
                            open_time = "10:00",
                            phone_number = "+78004444434",
                            restaurantName = "Бургер Кинг",
                            status = 1,
                            user_id = new Guid("1993856e-2f5c-4790-a3d4-33e6a5718b47")
                        });
                });

            modelBuilder.Entity("ORM_Components.Tables.ReviewTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("client_id")
                        .HasColumnType("uuid");

                    b.Property<string>("comment")
                        .HasColumnType("text");

                    b.Property<Guid>("courier_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("order_id")
                        .HasColumnType("uuid");

                    b.Property<int>("rating")
                        .HasColumnType("integer");

                    b.Property<Guid>("restaurant_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("review_date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("reviewTable");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9ae9cea3-d065-4c5f-84bf-3485da8295d6"),
                            client_id = new Guid("1993856e-2f5c-4790-a3d4-33e6a5718b47"),
                            courier_id = new Guid("729d9e64-faf1-439b-95f9-5a29a0e3e969"),
                            order_id = new Guid("871c8f7f-c4b1-46b3-b959-a6ccfbee534b"),
                            rating = 5,
                            restaurant_id = new Guid("54d33061-3691-4b7d-a60c-c53ef2e4eb4e"),
                            review_date = new DateTime(2025, 3, 31, 18, 27, 4, 335, DateTimeKind.Utc).AddTicks(3064)
                        },
                        new
                        {
                            Id = new Guid("acc48a14-1e54-49df-89d7-54be073758ce"),
                            client_id = new Guid("1993856e-2f5c-4790-a3d4-33e6a5718b47"),
                            courier_id = new Guid("bbcad18c-4e90-4541-9b33-d661cec2fc5a"),
                            order_id = new Guid("dd932e2a-972b-4517-9c64-30e48b0bd052"),
                            rating = 4,
                            restaurant_id = new Guid("54d33061-3691-4b7d-a60c-c53ef2e4eb4e"),
                            review_date = new DateTime(2025, 3, 31, 18, 27, 4, 335, DateTimeKind.Utc).AddTicks(3069)
                        });
                });

            modelBuilder.Entity("ORM_Components.Tables.UserTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("address")
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .HasColumnType("text");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("last_name")
                        .HasColumnType("text");

                    b.Property<long>("money_value")
                        .HasColumnType("bigint");

                    b.Property<string>("photo_url")
                        .HasColumnType("text");

                    b.Property<string[]>("roles")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<long>("telegram_chat_id")
                        .HasColumnType("bigint");

                    b.Property<long>("telegram_id")
                        .HasColumnType("bigint");

                    b.Property<string>("username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("userTable");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1993856e-2f5c-4790-a3d4-33e6a5718b47"),
                            address = "улица Шолмова, 7",
                            email = "",
                            first_name = "Антон (Study)",
                            last_name = "",
                            money_value = 5000L,
                            photo_url = "https://t.me/i/userpic/320/YC895p02kbd-O-aU-F49vK8j1qFbmbObwS_DaaPkKdg.svg",
                            roles = new[] { "Client", "Admin", "Courier" },
                            telegram_chat_id = 1006365928L,
                            telegram_id = 1006365928L,
                            username = "studywhite"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
