// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ORM_Components;

#nullable disable

namespace ORM_Components.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ORM_Components.Tables.BankCardTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("card_number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("cvv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("money_value")
                        .HasColumnType("bigint");

                    b.Property<string>("name_card")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("bankCardTable");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e11ba92a-649b-4ea7-8881-c4d7840be3a0"),
                            card_number = "0000 1234 0000 4321",
                            cvv = "123",
                            money_value = 1000000L,
                            name_card = "Virtual Card"
                        });
                });

            modelBuilder.Entity("ORM_Components.Tables.BasketTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("food_item_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("basketTable");
                });

            modelBuilder.Entity("ORM_Components.Tables.CardUsersTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("card_number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("cvv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("money_value")
                        .HasColumnType("bigint");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("cardUsersTable");
                });

            modelBuilder.Entity("ORM_Components.Tables.CourierTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("car_number")
                        .HasColumnType("text");

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.Property<Guid>("userId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("courierTable");
                });

            modelBuilder.Entity("ORM_Components.Tables.OrderItemsTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("order_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("restaraunt_food_item")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("orderItemsTable");
                });

            modelBuilder.Entity("ORM_Components.Tables.OrderStatusHistoryTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("order_id")
                        .HasColumnType("uuid");

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("status_datetime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("orderHistory");
                });

            modelBuilder.Entity("ORM_Components.Tables.OrderTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("client_address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("client_id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("courier_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("order_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("restaurant_id")
                        .HasColumnType("uuid");

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.Property<long>("total_price")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("orderTable");
                });

            modelBuilder.Entity("ORM_Components.Tables.PayTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("card_number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("pay_status")
                        .HasColumnType("integer");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("payTable");
                });

            modelBuilder.Entity("ORM_Components.Tables.RequestTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("courier_id")
                        .HasColumnType("uuid");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("restaurant_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("time_add")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("requestTable");
                });

            modelBuilder.Entity("ORM_Components.Tables.RestaurantFoodItemsTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("calories")
                        .HasColumnType("integer");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("price")
                        .HasColumnType("bigint");

                    b.Property<Guid>("restaurant_id")
                        .HasColumnType("uuid");

                    b.Property<int>("weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("restaurantFoodItemsTable");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7337f7f8-b155-41b0-898c-17d71c47a46f"),
                            calories = 0,
                            image = "/app/migrated_images/Vkusno/chikenburger.png",
                            name = "Чикенбургер",
                            price = 82L,
                            restaurant_id = new Guid("54d33061-3691-4b7d-a60c-c53ef2e4eb4e"),
                            weight = 0
                        },
                        new
                        {
                            Id = new Guid("657a1f09-b1e8-446d-a604-6beb679f00c4"),
                            calories = 0,
                            image = "/app/migrated_images/Vkusno/bighit.png",
                            name = "Биг Хит",
                            price = 223L,
                            restaurant_id = new Guid("54d33061-3691-4b7d-a60c-c53ef2e4eb4e"),
                            weight = 0
                        },
                        new
                        {
                            Id = new Guid("7012ae00-248b-4634-a1e2-6fcbb88107ae"),
                            calories = 0,
                            image = "/app/migrated_images/Vkusno/cheezeburger.png",
                            name = "Чизбургер",
                            price = 101L,
                            restaurant_id = new Guid("54d33061-3691-4b7d-a60c-c53ef2e4eb4e"),
                            weight = 0
                        },
                        new
                        {
                            Id = new Guid("5f3605bd-038e-4fb3-913f-84568687cde8"),
                            calories = 0,
                            image = "/app/migrated_images/Vkusno/bigspecial.png",
                            name = "Биг спешиал",
                            price = 352L,
                            restaurant_id = new Guid("54d33061-3691-4b7d-a60c-c53ef2e4eb4e"),
                            weight = 0
                        },
                        new
                        {
                            Id = new Guid("e27ba0c1-7ebb-4904-8802-636a1b92687e"),
                            calories = 0,
                            image = "/app/migrated_images/Vkusno/cezarroll.png",
                            name = "Цезарь Ролл",
                            price = 242L,
                            restaurant_id = new Guid("54d33061-3691-4b7d-a60c-c53ef2e4eb4e"),
                            weight = 0
                        },
                        new
                        {
                            Id = new Guid("c5d9eac3-c007-4461-bd44-b56b0040c670"),
                            calories = 0,
                            image = "/app/migrated_images/Vkusno/doublecheezeburger.png",
                            name = "Двойной Чизбургер",
                            price = 195L,
                            restaurant_id = new Guid("54d33061-3691-4b7d-a60c-c53ef2e4eb4e"),
                            weight = 0
                        },
                        new
                        {
                            Id = new Guid("100461ce-42f5-43f9-8017-bda75881c466"),
                            calories = 0,
                            image = "/app/migrated_images/Vkusno/chikenpremiere.png",
                            name = "Чикен Премьер",
                            price = 214L,
                            restaurant_id = new Guid("54d33061-3691-4b7d-a60c-c53ef2e4eb4e"),
                            weight = 0
                        },
                        new
                        {
                            Id = new Guid("a9c37a68-df76-4719-bab2-f7e014407b22"),
                            calories = 0,
                            image = "/app/migrated_images/Vkusno/potatofreesred.png",
                            name = "Картофель Фри средний",
                            price = 112L,
                            restaurant_id = new Guid("54d33061-3691-4b7d-a60c-c53ef2e4eb4e"),
                            weight = 0
                        },
                        new
                        {
                            Id = new Guid("048aa391-77fa-4117-9e23-e34c7c1f2613"),
                            calories = 0,
                            image = "/app/migrated_images/Vkusno/naggets6.png",
                            name = "Наггетсы (6 шт)",
                            price = 109L,
                            restaurant_id = new Guid("54d33061-3691-4b7d-a60c-c53ef2e4eb4e"),
                            weight = 0
                        },
                        new
                        {
                            Id = new Guid("2f672f99-79c0-4ecb-a69b-91871f018414"),
                            calories = 0,
                            image = "/app/migrated_images/Vkusno/capuchinosred.png",
                            name = "Капучино (сред.)",
                            price = 134L,
                            restaurant_id = new Guid("54d33061-3691-4b7d-a60c-c53ef2e4eb4e"),
                            weight = 0
                        },
                        new
                        {
                            Id = new Guid("372a9739-6f7e-49fc-803a-829120fe1731"),
                            calories = 0,
                            image = "/app/migrated_images/Vkusno/vishnyapirojok.png",
                            name = "Пирожок Вишневый",
                            price = 84L,
                            restaurant_id = new Guid("54d33061-3691-4b7d-a60c-c53ef2e4eb4e"),
                            weight = 0
                        });
                });

            modelBuilder.Entity("ORM_Components.Tables.RestaurantTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("close_time")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("imagePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("open_time")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("phone_number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("restaurantName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("restaurantTable");

                    b.HasData(
                        new
                        {
                            Id = new Guid("54d33061-3691-4b7d-a60c-c53ef2e4eb4e"),
                            address = "ул. Шолмова 5",
                            close_time = "21:00",
                            description = "Отличный тестовый ресторан",
                            imagePath = "/app/migrated_images/vkusno.jpg",
                            open_time = "10:00",
                            phone_number = "+78005555535",
                            restaurantName = "Вкусно и точка",
                            status = 1,
                            user_id = new Guid("1993856e-2f5c-4790-a3d4-33e6a5718b47")
                        },
                        new
                        {
                            Id = new Guid("3f8cc0c7-afa7-4bc7-89aa-b207d68f417d"),
                            address = "ул. Шолмова 3",
                            close_time = "20:00",
                            description = "Хороший тестовый ресторан",
                            imagePath = "/app/migrated_images/burgerking.jpg",
                            open_time = "10:00",
                            phone_number = "+78004444434",
                            restaurantName = "Бургер Кинг",
                            status = 1,
                            user_id = new Guid("1993856e-2f5c-4790-a3d4-33e6a5718b47")
                        });
                });

            modelBuilder.Entity("ORM_Components.Tables.ReviewTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("client_id")
                        .HasColumnType("uuid");

                    b.Property<string>("comment")
                        .HasColumnType("text");

                    b.Property<Guid>("courier_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("order_id")
                        .HasColumnType("uuid");

                    b.Property<int>("rating")
                        .HasColumnType("integer");

                    b.Property<Guid>("restaurant_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("review_date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("reviewTable");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0e9c689-0691-4557-aa37-41a7170ec26a"),
                            client_id = new Guid("1993856e-2f5c-4790-a3d4-33e6a5718b47"),
                            courier_id = new Guid("1993856e-2f5c-4790-a3d4-33e6a5718b47"),
                            order_id = new Guid("aa17db13-2763-4ce3-a590-d91755a058ea"),
                            rating = 5,
                            restaurant_id = new Guid("54d33061-3691-4b7d-a60c-c53ef2e4eb4e"),
                            review_date = new DateTime(2026, 3, 31, 1, 31, 11, 775, DateTimeKind.Utc).AddTicks(6684)
                        },
                        new
                        {
                            Id = new Guid("68e96c22-4399-44d4-b932-cac97908b7c4"),
                            client_id = new Guid("1993856e-2f5c-4790-a3d4-33e6a5718b47"),
                            courier_id = new Guid("1993856e-2f5c-4790-a3d4-33e6a5718b47"),
                            order_id = new Guid("447c4f11-51e6-4398-927d-b38148cff2ed"),
                            rating = 4,
                            restaurant_id = new Guid("54d33061-3691-4b7d-a60c-c53ef2e4eb4e"),
                            review_date = new DateTime(2026, 3, 31, 1, 31, 11, 775, DateTimeKind.Utc).AddTicks(6688)
                        });
                });

            modelBuilder.Entity("ORM_Components.Tables.UserTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("address")
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .HasColumnType("text");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("last_name")
                        .HasColumnType("text");

                    b.Property<long>("money_value")
                        .HasColumnType("bigint");

                    b.Property<string>("photo_url")
                        .HasColumnType("text");

                    b.Property<string[]>("roles")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<long>("vk_id")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("userTable");
                });
#pragma warning restore 612, 618
        }
    }
}
