// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ORM_Components;

#nullable disable

namespace ORM_Components.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ORM_Components.Tables.BankCardTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("card_number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("cvv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("money_value")
                        .HasColumnType("bigint");

                    b.Property<string>("name_card")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("bankCardTable");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e11ba92a-649b-4ea7-8881-c4d7840be3a0"),
                            card_number = "0000 1234 0000 4321",
                            cvv = "123",
                            money_value = 1000000L,
                            name_card = "Virtual Card"
                        });
                });

            modelBuilder.Entity("ORM_Components.Tables.BasketTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("food_item_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("basketTable");
                });

            modelBuilder.Entity("ORM_Components.Tables.CardUsersTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("card_number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("cvv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("money_value")
                        .HasColumnType("bigint");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("cardUsersTable");
                });

            modelBuilder.Entity("ORM_Components.Tables.CourierTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("car_number")
                        .HasColumnType("text");

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.Property<Guid>("userId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("courierTable");
                });

            modelBuilder.Entity("ORM_Components.Tables.OrderItemsTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("order_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("restaraunt_food_item")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("orderItemsTable");
                });

            modelBuilder.Entity("ORM_Components.Tables.OrderStatusHistoryTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("order_id")
                        .HasColumnType("uuid");

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("status_datetime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("orderHistory");
                });

            modelBuilder.Entity("ORM_Components.Tables.OrderTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("client_address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("client_id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("courier_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("order_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("restaurant_id")
                        .HasColumnType("uuid");

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.Property<long>("total_price")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("orderTable");
                });

            modelBuilder.Entity("ORM_Components.Tables.PayTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("card_number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("pay_status")
                        .HasColumnType("integer");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("payTable");
                });

            modelBuilder.Entity("ORM_Components.Tables.RequestTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("courier_id")
                        .HasColumnType("uuid");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("restaurant_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("time_add")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("requestTable");
                });

            modelBuilder.Entity("ORM_Components.Tables.RestaurantFoodItemsTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("calories")
                        .HasColumnType("integer");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("price")
                        .HasColumnType("bigint");

                    b.Property<Guid>("restaurant_id")
                        .HasColumnType("uuid");

                    b.Property<int>("weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("restaurantFoodItemsTable");

                    b.HasData(
                        new
                        {
                            Id = new Guid("957ab8e0-668d-47c1-8ef4-682034f4203b"),
                            calories = 0,
                            image = "/app/migrated_images/Vkusno/chikenburger.png",
                            name = "Чикенбургер",
                            price = 82L,
                            restaurant_id = new Guid("54d33061-3691-4b7d-a60c-c53ef2e4eb4e"),
                            weight = 0
                        },
                        new
                        {
                            Id = new Guid("f395516d-3c48-4f59-a602-9b7dd0525e3e"),
                            calories = 0,
                            image = "/app/migrated_images/Vkusno/bighit.png",
                            name = "Биг Хит",
                            price = 223L,
                            restaurant_id = new Guid("54d33061-3691-4b7d-a60c-c53ef2e4eb4e"),
                            weight = 0
                        },
                        new
                        {
                            Id = new Guid("cd51f618-264d-409b-a590-dd13f68fd081"),
                            calories = 0,
                            image = "/app/migrated_images/Vkusno/cheezeburger.png",
                            name = "Чизбургер",
                            price = 101L,
                            restaurant_id = new Guid("54d33061-3691-4b7d-a60c-c53ef2e4eb4e"),
                            weight = 0
                        },
                        new
                        {
                            Id = new Guid("f39ea95d-c987-4efa-af6b-cc85443f40f4"),
                            calories = 0,
                            image = "/app/migrated_images/Vkusno/bigspecial.png",
                            name = "Биг спешиал",
                            price = 352L,
                            restaurant_id = new Guid("54d33061-3691-4b7d-a60c-c53ef2e4eb4e"),
                            weight = 0
                        },
                        new
                        {
                            Id = new Guid("4b9e24af-0d45-4e4b-8c28-6fa3eb569995"),
                            calories = 0,
                            image = "/app/migrated_images/Vkusno/cezarroll.png",
                            name = "Цезарь Ролл",
                            price = 242L,
                            restaurant_id = new Guid("54d33061-3691-4b7d-a60c-c53ef2e4eb4e"),
                            weight = 0
                        },
                        new
                        {
                            Id = new Guid("b970779e-6b59-4a63-bc4e-6c23bdc32f37"),
                            calories = 0,
                            image = "/app/migrated_images/Vkusno/doublecheezeburger.png",
                            name = "Двойной Чизбургер",
                            price = 195L,
                            restaurant_id = new Guid("54d33061-3691-4b7d-a60c-c53ef2e4eb4e"),
                            weight = 0
                        },
                        new
                        {
                            Id = new Guid("23ed9a27-a91e-4de3-a86d-17511da3bd63"),
                            calories = 0,
                            image = "/app/migrated_images/Vkusno/chikenpremiere.png",
                            name = "Чикен Премьер",
                            price = 214L,
                            restaurant_id = new Guid("54d33061-3691-4b7d-a60c-c53ef2e4eb4e"),
                            weight = 0
                        },
                        new
                        {
                            Id = new Guid("73976fe1-78a9-4923-95f6-b851f2e4613d"),
                            calories = 0,
                            image = "/app/migrated_images/Vkusno/potatofreesred.png",
                            name = "Картофель Фри средний",
                            price = 112L,
                            restaurant_id = new Guid("54d33061-3691-4b7d-a60c-c53ef2e4eb4e"),
                            weight = 0
                        },
                        new
                        {
                            Id = new Guid("9a5b991e-75ae-4f9a-b071-a9c877fc1ea0"),
                            calories = 0,
                            image = "/app/migrated_images/Vkusno/naggets6.png",
                            name = "Наггетсы (6 шт)",
                            price = 109L,
                            restaurant_id = new Guid("54d33061-3691-4b7d-a60c-c53ef2e4eb4e"),
                            weight = 0
                        },
                        new
                        {
                            Id = new Guid("576cc2a8-510d-4486-af8b-0e08ab413b20"),
                            calories = 0,
                            image = "/app/migrated_images/Vkusno/capuchinosred.png",
                            name = "Капучино (сред.)",
                            price = 134L,
                            restaurant_id = new Guid("54d33061-3691-4b7d-a60c-c53ef2e4eb4e"),
                            weight = 0
                        },
                        new
                        {
                            Id = new Guid("f8546637-d2b5-4eda-b3b6-1cd6235a7d91"),
                            calories = 0,
                            image = "/app/migrated_images/Vkusno/vishnyapirojok.png",
                            name = "Пирожок Вишневый",
                            price = 84L,
                            restaurant_id = new Guid("54d33061-3691-4b7d-a60c-c53ef2e4eb4e"),
                            weight = 0
                        });
                });

            modelBuilder.Entity("ORM_Components.Tables.RestaurantTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("close_time")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("imagePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("open_time")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("phone_number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("restaurantName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("restaurantTable");

                    b.HasData(
                        new
                        {
                            Id = new Guid("54d33061-3691-4b7d-a60c-c53ef2e4eb4e"),
                            address = "ул. Шолмова 5",
                            close_time = "21:00",
                            description = "Отличный тестовый ресторан",
                            imagePath = "/app/migrated_images/vkusno.jpg",
                            open_time = "10:00",
                            phone_number = "+78005555535",
                            restaurantName = "Вкусно и точка",
                            status = 1,
                            user_id = new Guid("1993856e-2f5c-4790-a3d4-33e6a5718b47")
                        },
                        new
                        {
                            Id = new Guid("fa0a60fc-85d5-4c4f-b3ae-4703883b61a5"),
                            address = "ул. Шолмова 3",
                            close_time = "20:00",
                            description = "Хороший тестовый ресторан",
                            imagePath = "/app/migrated_images/burgerking.jpg",
                            open_time = "10:00",
                            phone_number = "+78004444434",
                            restaurantName = "Бургер Кинг",
                            status = 1,
                            user_id = new Guid("1993856e-2f5c-4790-a3d4-33e6a5718b47")
                        });
                });

            modelBuilder.Entity("ORM_Components.Tables.ReviewTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("client_id")
                        .HasColumnType("uuid");

                    b.Property<string>("comment")
                        .HasColumnType("text");

                    b.Property<Guid>("courier_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("order_id")
                        .HasColumnType("uuid");

                    b.Property<int>("rating")
                        .HasColumnType("integer");

                    b.Property<Guid>("restaurant_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("review_date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("reviewTable");

                    b.HasData(
                        new
                        {
                            Id = new Guid("973d7ba0-d039-4713-a175-9ea7599eed0f"),
                            client_id = new Guid("1993856e-2f5c-4790-a3d4-33e6a5718b47"),
                            courier_id = new Guid("1993856e-2f5c-4790-a3d4-33e6a5718b47"),
                            order_id = new Guid("bca582ed-61e3-4c6c-b424-8457f0bd23ab"),
                            rating = 5,
                            restaurant_id = new Guid("54d33061-3691-4b7d-a60c-c53ef2e4eb4e"),
                            review_date = new DateTime(2025, 4, 2, 17, 5, 9, 188, DateTimeKind.Utc).AddTicks(4170)
                        },
                        new
                        {
                            Id = new Guid("147d7a74-5263-4816-bdab-b4807f7197d2"),
                            client_id = new Guid("1993856e-2f5c-4790-a3d4-33e6a5718b47"),
                            courier_id = new Guid("1993856e-2f5c-4790-a3d4-33e6a5718b47"),
                            order_id = new Guid("6cae7028-857c-49cc-912a-a2ebc451dfae"),
                            rating = 4,
                            restaurant_id = new Guid("54d33061-3691-4b7d-a60c-c53ef2e4eb4e"),
                            review_date = new DateTime(2025, 4, 2, 17, 5, 9, 188, DateTimeKind.Utc).AddTicks(4175)
                        });
                });

            modelBuilder.Entity("ORM_Components.Tables.UserTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("address")
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .HasColumnType("text");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("last_name")
                        .HasColumnType("text");

                    b.Property<long>("money_value")
                        .HasColumnType("bigint");

                    b.Property<string>("photo_url")
                        .HasColumnType("text");

                    b.Property<string[]>("roles")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<long>("telegram_chat_id")
                        .HasColumnType("bigint");

                    b.Property<long>("telegram_id")
                        .HasColumnType("bigint");

                    b.Property<string>("username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("userTable");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1993856e-2f5c-4790-a3d4-33e6a5718b47"),
                            address = "улица Шолмова, 7",
                            email = "",
                            first_name = "Антон (Study)",
                            last_name = "",
                            money_value = 5000L,
                            photo_url = "https://t.me/i/userpic/320/YC895p02kbd-O-aU-F49vK8j1qFbmbObwS_DaaPkKdg.svg",
                            roles = new[] { "Client", "Admin", "Courier" },
                            telegram_chat_id = 1006365928L,
                            telegram_id = 1006365928L,
                            username = "studywhite"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
